version: '3.8'
services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    
    image: gowthamneo1/backend-image:latest
    volumes:
      - ./Backend:/app  
    ports:
      - "3000:3000"
    depends_on:
      - db

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    image: gowthamneo1/frontend-image:latest
    volumes:
      - ./Frontend:/app  
    ports:
      - "5173:5173"
    

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Gowtham.psql
      POSTGRES_DB: Sports-center_development
    volumes:
      - postgres_data:/var/lib/postgresql/data


volumes:
  postgres_data:


